window:
  size: [ 1920, 1080 ]
  units: pix

environment:
  first_color: [ 0xff, 0, 0 ]
  second_color: [ 0xff, 0, 0 ]
  positive_reward: 70
  red: [ 20, 40, 20, 20 ]
  green: [ 20, 40, 20, 20 ]

checkerboard:
  size: 128
  # The positions of the center of the stimulus in the stimulus units
  pos_left: [ 320, 180 ]
  pos_right: [ -320, -180 ]